import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { z } from "zod";
import { allTools } from "../src/tools/defs/index.js";
import type { AnyToolDef } from "../src/tools/defs/defineTool.js";
import { ALL_PERMISSION_GROUPS } from "../src/tools/permissionGroups.js";

const OUT_PATH = "docs/tools/catalog.md";

function describeZod(schema: z.ZodTypeAny, depth = 0): string {
  const indent = "  ".repeat(depth);
  const def = (schema as unknown as { _def?: { typeName?: string; description?: string } })._def;
  const typeName = def?.typeName ?? "unknown";
  const description = (schema.description ?? def?.description ?? "").trim();
  const optional = schema.isOptional?.() ?? false;
  const nullable = schema.isNullable?.() ?? false;

  let type = "unknown";
  let inner = "";

  switch (typeName) {
    case "ZodString":
      type = "string";
      break;
    case "ZodNumber":
      type = "number";
      break;
    case "ZodBoolean":
      type = "boolean";
      break;
    case "ZodEnum": {
      const values = (schema as unknown as { options?: readonly string[] }).options ?? [];
      type = `enum(${values.map((v) => JSON.stringify(v)).join(" | ")})`;
      break;
    }
    case "ZodArray": {
      const el = (schema as unknown as { element: z.ZodTypeAny }).element;
      type = `array<${describeZod(el, depth + 1).split("\n")[0]}>`;
      break;
    }
    case "ZodObject": {
      type = "object";
      const shape = (schema as unknown as z.ZodObject<z.ZodRawShape>).shape;
      const lines: string[] = [];
      for (const [k, v] of Object.entries(shape)) {
        lines.push(`${indent}  - \`${k}\`: ${describeZod(v, depth + 1)}`);
      }
      inner = "\n" + lines.join("\n");
      break;
    }
    case "ZodRecord":
      type = "record<string, unknown>";
      break;
    case "ZodOptional": {
      const wrapped = (schema as unknown as { unwrap: () => z.ZodTypeAny }).unwrap();
      return describeZod(wrapped, depth) + (description ? "" : "");
    }
    case "ZodDefault": {
      const wrapped = (schema as unknown as { _def: { innerType: z.ZodTypeAny; defaultValue: () => unknown } })._def;
      const dv = wrapped.defaultValue();
      const inside = describeZod(wrapped.innerType, depth);
      return `${inside} (default: ${JSON.stringify(dv)})`;
    }
    case "ZodNullable": {
      const wrapped = (schema as unknown as { unwrap: () => z.ZodTypeAny }).unwrap();
      return `${describeZod(wrapped, depth)} | null`;
    }
    case "ZodLiteral": {
      const v = (schema as unknown as { value: unknown }).value;
      type = `literal(${JSON.stringify(v)})`;
      break;
    }
    case "ZodUnion": {
      const opts = (schema as unknown as { options: z.ZodTypeAny[] }).options;
      type = opts.map((o) => describeZod(o, depth + 1).split("\n")[0]).join(" | ");
      break;
    }
    case "ZodUnknown":
    case "ZodAny":
      type = "unknown";
      break;
  }

  const suffix: string[] = [];
  if (optional) suffix.push("optional");
  if (nullable) suffix.push("nullable");
  const suffixStr = suffix.length > 0 ? ` _(${suffix.join(", ")})_` : "";
  const descStr = description ? ` — ${description}` : "";
  return `${type}${suffixStr}${descStr}${inner}`;
}

function renderTool(t: AnyToolDef): string {
  const lines: string[] = [];
  lines.push(`### \`${t.name}\``);
  lines.push("");
  lines.push(t.description);
  lines.push("");
  lines.push(`- **Group:** \`${t.group}\``);
  lines.push(`- **Auth method:** ${t.authMethod}`);
  lines.push(`- **Destructive:** ${t.destructive ? "yes (commit-positive consent enforced)" : "no"}`);
  lines.push(`- **Requires cloudId:** ${t.needsCloudId ? "yes" : "no"}`);

  const obj = t.inputSchema as unknown as z.ZodObject<z.ZodRawShape>;
  const shape = obj.shape;
  const keys = Object.keys(shape);
  if (keys.length === 0) {
    lines.push("- **Input:** _(no parameters)_");
  } else {
    lines.push("- **Input:**");
    for (const k of keys) {
      lines.push(`  - \`${k}\`: ${describeZod(shape[k], 1)}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const tools = allTools();
  const byGroup = new Map<string, AnyToolDef[]>();
  for (const t of tools) {
    const arr = byGroup.get(t.group) ?? [];
    arr.push(t);
    byGroup.set(t.group, arr);
  }

  const sections: string[] = [];
  sections.push("# Tool catalog");
  sections.push("");
  sections.push(
    "_This file is generated by `npm run docs:tools` from the live `defineTool` registry. Do not edit by hand._",
  );
  sections.push("");
  sections.push(`Total tools registered: **${tools.length}**.`);
  sections.push("");
  sections.push("## Tools by permission group");
  sections.push("");

  for (const g of ALL_PERMISSION_GROUPS) {
    const list = byGroup.get(g);
    if (!list || list.length === 0) continue;
    sections.push(`### \`${g}\` (${list.length} tools)`);
    sections.push("");
    for (const t of list.sort((a, b) => a.name.localeCompare(b.name))) {
      sections.push(renderTool(t));
    }
    sections.push("---");
    sections.push("");
  }

  const out = sections.join("\n");
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, out, "utf8");
  process.stdout.write(`Wrote ${OUT_PATH} (${tools.length} tools)\n`);
}

main();
